services:
  - type: web
    name: tarkov-quest-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT scraper:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
